#!/usr/bin/env bash
# Two-Mac QA: local simulation + checklist for physical machines.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  PeekNook Two-Mac PDF Sync QA                            ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

echo "▶ Step 1: Local simulation (same machine, Mac A→B)…"
bash "$ROOT/scripts/peeknook-pdf-sync-verify.sh"
echo ""

echo "▶ Step 2: General sync smoke…"
bash "$ROOT/scripts/peeknook-sync-verify.sh"
echo ""

echo "▶ Step 3: Physical two-Mac checklist"
echo ""
echo "  Prerequisites (both Macs):"
echo "    • PeekNook API running (./scripts/peeknook-backend.sh or .app)"
echo "    • Same cloud account (PeekNook Cloud or self-hosted :8090)"
echo "    • Network access to cloud URL"
echo ""
echo "  Machine A (upload + push):"
echo "    export PEEKNOOK_CLOUD_EMAIL=you@example.com"
echo "    export PEEKNOOK_CLOUD_PASSWORD=your-password"
echo "    export PEEKNOOK_CLOUD_URL=https://your-cloud.example.com"
echo "    ./scripts/peeknook-pdf-sync-two-mac.sh push"
echo "    → note source_id from output"
echo ""
echo "  Machine B (pull + import):"
echo "    export PEEKNOOK_CLOUD_EMAIL=you@example.com"
echo "    export PEEKNOOK_CLOUD_PASSWORD=your-password"
echo "    export PEEKNOOK_CLOUD_URL=https://your-cloud.example.com"
echo "    export PEEKNOOK_SYNC_SOURCE_ID=<source_id from A>"
echo "    ./scripts/peeknook-pdf-sync-two-mac.sh pull"
echo ""
echo "  Verify on B:"
echo "    • Open http://localhost:5173/notebooks"
echo "    • PDF appears under the synced notebook"
echo "    • Settings → last sync status = ok"
echo ""
echo "  After physical test, record sign-off:"
echo "    export PEEKNOOK_SYNC_SOURCE_ID=<source_id from A>"
echo "    ./scripts/peeknook-two-mac-physical-record.sh"
echo ""
echo "  Local simulation (one machine): ./scripts/peeknook-pdf-sync-two-mac.sh auto"
echo ""
echo "✅ Automated QA passed. Complete physical checklist on two Macs when ready."
